/**
 * Standardized Domain Error Codes for Dayflow HRMS
 */
export const ERROR_CODES = {
  // Authentication & Session
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',

  // Authorization & Permissions
  FORBIDDEN: 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  CROSS_TENANT_ACCESS_DENIED: 'CROSS_TENANT_ACCESS_DENIED',

  // Validation & Input
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  MALFORMED_PAYLOAD: 'MALFORMED_PAYLOAD',

  // Resources
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  DUPLICATE_ENTITY: 'DUPLICATE_ENTITY',

  // Domain Business Rules
  BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
  CIRCULAR_HIERARCHY_ERROR: 'CIRCULAR_HIERARCHY_ERROR',
  IMMUTABLE_RECORD_ERROR: 'IMMUTABLE_RECORD_ERROR',

  // Server
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES] | string;
